# Notes on test batteries: 
# 1) Format is battery_id: (battery_name, [subtest_ids])
# 2) The order of the subtest ids is not necessarily the same as the
# order the battery was administered.
batteries: 
  14: ['old_short_order3', [29, 28, 30, 27, 26]]
  17: ['default_old', [29, 28, 30, 27, 32, 31]] 
  25: ['Research_cw_experiment', [29, 28, 33, 30, 27, 32, 31]]  
  26: ['verbal_list_learning', [36, 39, 40, 29, 28, 33, 30, 27, 32, 38, 37]] 
  32: ['wmva_test', [29, 38, 28, 33, 39, 40, 30, 27, 31]]
  39: ['subscriber_default_old', [29, 38, 28, 33, 39, 40, 30, 31]]
  50: ['subscriber_default_new', [29, 45, 43, 44, 39, 40, 30, 31]]
  60: ['default', [54, 52, 53, 55, 51]]
  
# Notes on the subtests:
# 1) Format is specific_subtest_id: [descriptive name, version number, 
    # IDs of other versions of the same subtest]
# 2) The specific_subtest_id distinguishes different versions of the same subtest;
# the general_subtest_ID field (below) distinguishes the type of subtest, but not
# the specific subtest version. 
# 3) For Lumos Labs internal use: Note that subtest version numbers differ from those used internally. 
subtests: 
  26: ['Go/no-go', 'Go/no-go', 'v1', 32]
  27: ['Divided visual attention', 'DVA', 'v1', 'None']
  28: ['Forward memory span', 'Forward mem.', 'v1', 43]
  29: ['Arithmetic reasoning', 'Arithmetic', 'v1', 'None']
  30: ['Grammatical reasoning', 'Grammar', 'v1', 'None']
  31: ['Progressive matrices', 'Matrices', 'v1', 'None']
  32: ['Go/no-go', 'Go/no-go', 'v2', 26]
  33: ['Reverse memory span', 'Reverse mem.', 'v1', 44]
  36: ['Verbal list learning', 'Lists', 'v1', 'None']
  37: ['Delayed verbal list learning', 'Delayed lists', 'v1', 'None']
  38: ['Digit symbol coding', 'Digit symbol', 'v1', 45]
  39: ['Trail making part A', 'Trails A', 'v1', 'None']
  40: ['Trail making part B', 'Trails B', 'v1', 'None']
  43: ['Forward memory span', 'Forward mem.', 'v2', 28]
  44: ['Reverse memory span', 'Reverse mem.', 'v2', 33]
  45: ['Digit symbol coding', 'Digit symbol', 'v2', 38]
  51: ['Scale balance', 'Scale balance', 'v1', 'None']
  52: ['Posner cueing', 'Posner', 'v1', 'None']
  53: ['Complex memory span', 'Complex mem.', 'v1', 'None']
  54: ['Object recognition', 'Object recog.', 'v1', 'None']
  55: ['Dual search', 'Dual search', 'v1', 'None']
  
education:
  1: 'Some high school'
  2: 'High school diploma / GED'
  3: 'Some college'
  4: 'College degree'
  5: 'Professional degree'
  6: "Master's degree"
  7: 'Ph.D.'
  8: "Associate's degree"
  99: 'Other'